name: push_platform_sdk
description: 统一推送中台 Flutter Client SDK
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.3
  uuid: ^4.4.0
  http: ^1.2.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
